server.port: 9000
spring:
  application:
    name: board-article-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/document
    username: root
    password: Abcd123@

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: reading-document-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false